[toolchain]
anchor_version = "0.32.1"
solana_version = "2.2.20"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[programs.devnet]
intent_gateway = "4dPJxe2R42G3GMdvpxz6JC3mxpzHzqFj9f8u3YTXaY55"

[programs.localnet]
intent_gateway = "4dPJxe2R42G3GMdvpxz6JC3mxpzHzqFj9f8u3YTXaY55"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn mocha --import=tsx --timeout 1000000 tests/**/*.ts"
